// ============================================================================
// File: simc_pi0_analysis.C
// Purpose: Analysis script for pure pi0 GEANT4 simulation
// Input: nps_excl_pi0_x60_4b_geant_500k_5ns.root (pure pi0 simulation)
// Output: Processed ROOT file with physics variables and weights
//
// SMEARING METHODOLOGY (Updated to match nps_sim_smearing.C):
// Two optional energy resolution models:
//   MODEL 1 (Simple): E_smeared = Gaus(μ × E, σ × √E)
//     - Data-driven, σ in GeV^(1/2), typically 0.02-0.04
//   MODEL 2 (3-term): E_smeared = Gaus(μ × E, σ × E × √((A/√E)² + (B/E)² + C²))
//     - Physics-motivated with A,B,C constants
// Set USE_SIMPLE_STOCHASTIC_MODEL to choose
// - Position smearing: ADDITIVE X_smeared = X_original + Gaus(0, sigma_pos)
//                              Y_smeared = Y_original + Gaus(0, sigma_pos)
//   Same sigma_pos is used for both x and y positions
// - Smearing parameters loaded from section_map.csv generated by nps_sim_smearing.C
// - Grid-based section assignment (8x8 default) must match nps_sim_smearing.C
// ============================================================================

#include <iostream>
#include <cmath>
#include <algorithm>
#include <vector>
#include <fstream>
#include <sstream>
#include <map>
#include "TFile.h"
#include "TTree.h"
#include "TH1F.h"
#include "TH2F.h"
#include "TCanvas.h"
#include "TMath.h"
#include "TLorentzVector.h"
#include "TRandom3.h"
#include "TGraph.h"
#include "TKey.h"

// Include shared helper files from src/ directory
#include "../src/nps_helper.h"
#include "../src/nps_physics_var.h"

using namespace std;

// ============================================================================
// Constants (use nps namespace constants from nps_helper.h)
// ============================================================================
const double BEAM_ENERGY = 10.538;      // GeV (hallc typical)
const double NORMFAC = 0.598673e9;      // Normalization factor for simulation
const double NEVENTS = 500000.0;        // Number of events in simulation
const int MAX_CLUS = 20;                // Maximum clusters
const double DEFAULT_TIME_WINDOW_WRT_150 = 10.0; // Time window for cluster selection
const double Y_MISPOINT = 0.0;          // Y mispointing offset (cm) - already taken care of in SIMC geometry, so set to 0 for analysis

// ============================================================================
// ENERGY RESOLUTION MODEL SELECTION (must match nps_sim_smearing.C)
// ============================================================================
const bool USE_SIMPLE_STOCHASTIC_MODEL = true;  // true = σ×√E, false = 3-term

// Model 2 constants (only used if USE_SIMPLE_STOCHASTIC_MODEL = false)
const double RESOLUTION_A = 0.0097;  // Stochastic term (0.97%)
const double RESOLUTION_B = 0.011;   // Noise term (1.1%)
const double RESOLUTION_C = 0.0114;  // Constant term (1.14%)
// ============================================================================
// Configuration Flags (hardcoded)
// ============================================================================
const bool USE_INDIVIDUAL_PHOTON_BRANCHES = false;  // Set to true to use phot1/phot2 branches instead of clusters

// Smearing file paths (relative to script location or absolute)
const char* SMEAR_FILE = "output/plots/x60_4b/out_smear.root";
const char* SMEAR_INTERP_FILE = "output/plots/x60_4b/out_smear_interpolated.root";
const char* SECTION_MAP_FILE = "output/plots/x60_4b/section_map.csv";

// ============================================================================
// Smearing Data Structures
// ============================================================================

struct SmearingCoeffs {
    double mu;           // Energy scale factor
    double sigma_E;      // Resolution parameter (√E units for simple, dimensionless for 3-term)
    double sigma_pos;    // Position resolution (additive, cm) - same for x and y
    // 3-term model parameters (only used if USE_SIMPLE_STOCHASTIC_MODEL = false)
    double res_A, res_B, res_C;
};

std::map<int, SmearingCoeffs> smearing_map;  // section -> coefficients

// ============================================================================
// Smearing Helper Functions
// ============================================================================

// Check if all smearing files exist
bool check_smearing_files_exist() {
    std::ifstream f1(SMEAR_FILE);
    std::ifstream f2(SMEAR_INTERP_FILE);
    std::ifstream f3(SECTION_MAP_FILE);
    return f1.good() && f2.good() && f3.good();
}

// Load section map from CSV
std::map<int, int> load_section_map(const char* filename) {
    std::map<int, int> section_map;
    std::ifstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Warning: Could not open section map file: " << filename << std::endl;
        return section_map;
    }
    
    std::string line;
    // Skip header line if present
    std::getline(file, line);
    
    while (std::getline(file, line)) {
        std::istringstream ss(line);
        std::string token;
        int block, section;
        
        if (std::getline(ss, token, ',')) {
            block = std::stoi(token);
            if (std::getline(ss, token, ',')) {
                section = std::stoi(token);
                section_map[block] = section;
            }
        }
    }
    
    std::cout << "Loaded section map with " << section_map.size() << " entries" << std::endl;
    return section_map;
}

// Load smearing coefficients from CSV file produced by nps_sim_smearing.C
// CSV format: ix,iy,xlo,xhi,ylo,yhi,n_data,n_sim,best_mu,best_sigma,best_sigma_pos_cm,res_A,res_B,res_C,best_chi2,ndf,chi2_ndf
bool load_smearing_coefficients(const char* smear_file, const char* smear_interp_file) {
    // Load from section_map.csv (primary source of fitted parameters)
    std::ifstream csv_file(SECTION_MAP_FILE);
    if (!csv_file.is_open()) {
        std::cerr << "Error: Cannot open CSV file: " << SECTION_MAP_FILE << std::endl;
        std::cerr << "Make sure nps_sim_smearing has been run to generate calibration files." << std::endl;
        return false;
    }
    
    std::cout << "Loading smearing coefficients from: " << SECTION_MAP_FILE << std::endl;
    
    std::string line;
    // Skip header line
    std::getline(csv_file, line);
    
    int sections_loaded = 0;
    while (std::getline(csv_file, line)) {
        if (line.empty()) continue;
        
        std::istringstream ss(line);
        std::string token;
        std::vector<std::string> tokens;
        
        // Parse CSV line
        while (std::getline(ss, token, ',')) {
            tokens.push_back(token);
        }
        
        // Need at least 14 columns: ix, iy, xlo, xhi, ylo, yhi, n_data, n_sim, best_mu, best_sigma, best_sigma_pos_cm, res_A, res_B, res_C
        if (tokens.size() < 14) continue;
        
        // Check if this section has valid fit results (non-empty mu, sigma, sigma_pos, and A,B,C)
        if (tokens[8].empty() || tokens[9].empty() || tokens[10].empty()) continue;
        
        try {
            int ix = std::stoi(tokens[0]);
            int iy = std::stoi(tokens[1]);
            double mu = std::stod(tokens[8]);
            double sigma = std::stod(tokens[9]);
            double sigma_pos = std::stod(tokens[10]);
            
            // Read res_A, res_B, res_C (may be empty for simple model)
            double res_A = (!tokens[11].empty()) ? std::stod(tokens[11]) : RESOLUTION_A;
            double res_B = (!tokens[12].empty()) ? std::stod(tokens[12]) : RESOLUTION_B;
            double res_C = (!tokens[13].empty()) ? std::stod(tokens[13]) : RESOLUTION_C;
            
            // Create unique section ID from grid indices
            int section_id = iy * 100 + ix;  // Assumes grid < 100x100
            
            // Store parameters
            smearing_map[section_id].mu = mu;
            smearing_map[section_id].sigma_E = sigma;
            smearing_map[section_id].sigma_pos = sigma_pos;
            smearing_map[section_id].res_A = res_A;
            smearing_map[section_id].res_B = res_B;
            smearing_map[section_id].res_C = res_C;
            
            sections_loaded++;
            
            if (sections_loaded <= 5) {
                std::cout << "  Section (" << ix << "," << iy << "): mu=" << mu 
                          << ", sigma=" << sigma << ", sigma_pos=" << sigma_pos << " cm" << std::endl;
            }
        } catch (const std::exception& e) {
            std::cerr << "Warning: Failed to parse line: " << line << std::endl;
            continue;
        }
    }
    
    csv_file.close();
    
    std::cout << "Loaded smearing coefficients for " << sections_loaded << " sections" << std::endl;
    
    // If no sections found in file, create default smearing for section 0
    if (smearing_map.empty()) {
        std::cout << "No smearing data in file, using default values" << std::endl;
        // Default: mu=1.0 (no scale shift), sigma_E=0.05 (5% resolution), no position smearing
        smearing_map[0] = {1.0, 0.05, 0.0, RESOLUTION_A, RESOLUTION_B, RESOLUTION_C}; // mu, sigma_E, sigma_pos, res_A, res_B, res_C
    }
    
    return true;
}

// Get section number from cluster position using grid-based assignment
// This must match the grid parameters used in nps_sim_smearing.C
// Typical grid: 9x9 sections, x=[-30,30] cm, y=[-36,36] cm
int get_section(double x, double y) {
    // Grid parameters (CRITICAL: must match those used in nps_sim_smearing.C)
    // WARNING: Update nx, ny, x_min, x_max, y_min, y_max to match your nps_sim_smearing run!
    const int nx = 7;
    const int ny = 7;
    const double x_min = -30.0;
    const double x_max = 30.0;
    const double y_min = -36.0;
    const double y_max = 36.0;
    
    // Check if position is within calorimeter bounds
    if (x < x_min || x > x_max || y < y_min || y > y_max) {
        return 0;  // Default section for out-of-bounds
    }
    
    // Calculate grid cell
    double base_wx = (x_max - x_min) / nx;
    double base_wy = (y_max - y_min) / ny;
    
    int ix = static_cast<int>((x - x_min) / base_wx);
    int iy = static_cast<int>((y - y_min) / base_wy);
    
    // Clamp to valid range [0, nx-1] and [0, ny-1]
    if (ix < 0) ix = 0;
    if (ix >= nx) ix = nx - 1;
    if (iy < 0) iy = 0;
    if (iy >= ny) iy = ny - 1;
    
    // Return section ID (must match encoding in load_smearing_coefficients)
    return iy * 100 + ix;
}

// Apply energy smearing with selected resolution model
// Model selection controlled by USE_SIMPLE_STOCHASTIC_MODEL
// This must match the methodology in nps_sim_smearing.C
double apply_energy_smearing(double energy, double mu, double sigma, double res_A, double res_B, double res_C) {
    if (energy <= 0) return 1e-6;
    if (sigma <= 0 || mu <= 0) return energy * mu;  // If no resolution, just apply scale
    
    // Compute energy-dependent resolution based on selected model
    double sigma_E;
    if (USE_SIMPLE_STOCHASTIC_MODEL) {
        // Simple stochastic: σ_E = σ × √E
        sigma_E = sigma * sqrt(energy);
    } else {
        // Full 3-term: σ_E = σ × E × √((A/√E)² + (B/E)² + C²)
        double A_sq = res_A * res_A;
        double B_sq = res_B * res_B;
        double C_sq = res_C * res_C;
        sigma_E = sigma * energy * sqrt(A_sq / energy + B_sq / (energy * energy) + C_sq);
    }
    
    // Generate smeared energy: Gaus(μ × E, σ_E)
    double E_scaled = mu * energy;
    double draw = gRandom->Gaus(E_scaled, sigma_E);
    if (draw <= 0) draw = 1e-6;  // Clamp to avoid non-positive energies
    return draw;
}

// Apply position smearing (additive): X_smeared = X_original + Gaus(0, sigma_pos)
// Same sigma_pos is used for both x and y positions
double apply_position_smearing(double position, double sigma_pos) {
    if (sigma_pos <= 0) return position;
    return position + gRandom->Gaus(0, sigma_pos);
}

// ============================================================================
// HMS cuts for simulation (no npesum, etotnorm available)
// ============================================================================
inline bool hms_electron_cuts_simulation(double h_delta, double h_gtr_th,
                                         double h_gtr_ph, double h_react_z) noexcept
{
    // Simulation doesn't have npesum and etotnorm, so we skip those cuts
    if (h_react_z < -4.0 || h_react_z > 4.0) return false;
    if (h_delta < -15.0 || h_delta > 15.0) return false;
    if (h_gtr_th < -0.1 || h_gtr_th > 0.1) return false;
    if (h_gtr_ph < -0.04 || h_gtr_ph > 0.04) return false;
    return true;
}

// ============================================================================
// Main Analysis Function
// ============================================================================

void simc_pi0_analysis()
{
    // Input file
    const char* input_file = "/w/hallc-scshelf2102/nps/singhav/geant4_simc/HallC_NPS/DVCS_evt_gen/DVCS/build/nps_excl_x60_4b_500k.root";
    const char* output_file = "output/plots/x60_4b/simc_pi0_analysis_output.root";
    const char* output_file_smeared = "output/plots/x60_4b/simc_pi0_analysis_output_smeared.root";
    
    // Check if smearing files exist
    bool use_smearing = check_smearing_files_exist();
    std::map<int, int> section_map;
    
    if (use_smearing) {
        std::cout << "\n=== Smearing enabled ==="  << std::endl;
        std::cout << "Smearing files found. Will produce both original and smeared outputs." << std::endl;
        
        // Load smearing data
        if (!load_smearing_coefficients(SMEAR_FILE, SMEAR_INTERP_FILE)) {
            std::cerr << "Failed to load smearing coefficients, disabling smearing" << std::endl;
            use_smearing = false;
        } else {
            section_map = load_section_map(SECTION_MAP_FILE);
        }
    } else {
        std::cout << "\n=== Smearing disabled ==="  << std::endl;
        std::cout << "Smearing files not found. Will produce only original output." << std::endl;
    }
    
    // Open input file
    TFile *infile = new TFile(input_file, "READ");
    if (!infile || infile->IsZombie()) {
        cerr << "Error: Cannot open input file " << input_file << endl;
        return;
    }
    
    TTree *tree = (TTree*) infile->Get("nerd");
    if (!tree) {
        cerr << "Error: Cannot find tree 'nerd' in input file" << endl;
        return;
    }
    
    cout << "Input file loaded: " << input_file << endl;
    cout << "Number of entries: " << tree->GetEntries() << endl;
    
    // Debug: List all branches
    cout << "\n=== Available branches in tree ===" << endl;
    TObjArray *branches = tree->GetListOfBranches();
    for (int i = 0; i < branches->GetEntries() && i < 30; i++) {
        TBranch *b = (TBranch*)branches->At(i);
        cout << "  " << b->GetName() << endl;
    }
    if (branches->GetEntries() > 30) {
        cout << "  ... and " << (branches->GetEntries() - 30) << " more branches" << endl;
    }
    cout << endl;
    
    // Cluster vectors (for default mode)
    vector<double> *clust_E = nullptr;
    vector<double> *clust_X = nullptr;
    vector<double> *clust_Y = nullptr;
    // Note: clust_T not available in simulation, will be set to 150.0 for all clusters
    
    // Individual photon branches
    Double_t phot1_Ecal = 0, phot1_hit_x = 0, phot1_hit_y = 0;
    Double_t phot2_Ecal = 0, phot2_hit_x = 0, phot2_hit_y = 0;
    Bool_t phot1_hit = false, phot2_hit = false;
    
    // Weight and HMS tracking variables
    Float_t Weight = 1.0;
    Float_t hsdelta = 0, hsyptar = 0, hsxptar = 0, hsytar = 0;
    Float_t sc_e_E = 0, sc_e_Px = 0, sc_e_Py = 0, sc_e_Pz = 0;  // Electron kinematics from simulation
    Double_t hreactz = 0;  // Reaction z position (calculated, not from branch)
    Float_t x_beam = 0;   // Beam x position at target from simulation
    Float_t vtx_z = 0;    // Vertex z position from simulation
    
    // ========================================================================
    // Set Branch Addresses for Input
    // ========================================================================
    
    if (USE_INDIVIDUAL_PHOTON_BRANCHES) {
        // Use individual photon branches
        tree->SetBranchAddress("phot1_Ecal", &phot1_Ecal);
        tree->SetBranchAddress("phot1_hit_x", &phot1_hit_x);
        tree->SetBranchAddress("phot1_hit_y", &phot1_hit_y);
        tree->SetBranchAddress("phot1_hit", &phot1_hit);
        tree->SetBranchAddress("phot2_Ecal", &phot2_Ecal);
        tree->SetBranchAddress("phot2_hit_x", &phot2_hit_x);
        tree->SetBranchAddress("phot2_hit_y", &phot2_hit_y);
        tree->SetBranchAddress("phot2_hit", &phot2_hit);
        tree->SetBranchAddress("Weight", &Weight);
        
        // HMS variables
        tree->SetBranchAddress("hsdelta", &hsdelta);
        tree->SetBranchAddress("hsyptar", &hsyptar);
        tree->SetBranchAddress("hsxptar", &hsxptar);
        tree->SetBranchAddress("hsytar", &hsytar);
        tree->SetBranchAddress("sc_e_E", &sc_e_E);
        tree->SetBranchAddress("sc_e_Px", &sc_e_Px);
        tree->SetBranchAddress("sc_e_Py", &sc_e_Py);
        tree->SetBranchAddress("sc_e_Pz", &sc_e_Pz);
        tree->SetBranchAddress("vtx_x", &x_beam);
        tree->SetBranchAddress("vtx_z", &vtx_z);
        
        // Verify branches exist
        if (!tree->GetBranch("phot1_hit")) {
            cerr << "Warning: phot1_hit branch not found" << endl;
        }
        if (!tree->GetBranch("phot2_hit")) {
            cerr << "Warning: phot2_hit branch not found" << endl;
        }
        
        cout << "Using individual photon branches (phot1/phot2)" << endl;
        
    } else {
        // Use cluster vectors (default)
        tree->SetBranchAddress("clust_E", &clust_E);
        tree->SetBranchAddress("clust_X", &clust_X);
        tree->SetBranchAddress("clust_Y", &clust_Y);
        // clust_T not available in simulation, will use 150.0
        tree->SetBranchAddress("Weight", &Weight);
        
        // HMS variables
        tree->SetBranchAddress("hsdelta", &hsdelta);
        tree->SetBranchAddress("hsyptar", &hsyptar);
        tree->SetBranchAddress("hsxptar", &hsxptar);
        tree->SetBranchAddress("hsytar", &hsytar);
        tree->SetBranchAddress("sc_e_E", &sc_e_E);
        tree->SetBranchAddress("sc_e_Px", &sc_e_Px);
        tree->SetBranchAddress("sc_e_Py", &sc_e_Py);
        tree->SetBranchAddress("sc_e_Pz", &sc_e_Pz);
        tree->SetBranchAddress("vtx_x", &x_beam);
        tree->SetBranchAddress("vtx_z", &vtx_z);
        
        cout << "Using cluster vectors (clust_E/X/Y)" << endl;
    }
    
    // ========================================================================
    // Create Output Files and Trees
    // ========================================================================
    
    TFile *outfile = new TFile(output_file, "RECREATE");
    TTree *outtree = new TTree("simulation", "Pi0 simulation Output");
    
    TFile *outfile_smeared = nullptr;
    TTree *outtree_smeared = nullptr;
    
    if (use_smearing) {
        outfile_smeared = new TFile(output_file_smeared, "RECREATE");
        outtree_smeared = new TTree("simulation", "Pi0 simulation Output (Smeared)");
    }
    
    // Output variables (original)
    Float_t out_clust_E[2];
    Float_t out_clust_X[2];
    Float_t out_clust_Y[2];
    Int_t out_nclust;
    Float_t out_mpi0;           // Pion invariant mass
    Float_t out_mmiss;          // Missing mass
    Float_t out_full_weight;    // Weighted weight
    Float_t out_Q2;             // Momentum transfer squared
    Float_t out_W;              // Invariant mass
    Float_t out_nu;             // Energy transfer
    Float_t out_xB;             // Bjorken x
    Float_t out_z;              // Energy fraction
    Float_t out_theta_e;        // Electron scattering angle
    
    // HMS variables
    Float_t out_hsdelta;
    Float_t out_hsyptar;
    Float_t out_hsxptar;
    Float_t out_hsytar;
    Float_t out_phi_azimuth;  // Azimuthal angle: atan2(py_e, px_e)
    Float_t out_hreactz;      // Calculated reaction z position
    Float_t out_theta_c;      // Electron scattering angle in xz plane: atan2(px_e, pz_e)
    Float_t out_vtx_z;        // Vertex z position
    
    // Smeared output variables (same structure)
    Float_t out_clust_E_sm[2];
    Float_t out_clust_X_sm[2];
    Float_t out_clust_Y_sm[2];
    Int_t out_nclust_sm;
    Float_t out_mpi0_sm;
    Float_t out_mmiss_sm;
    Float_t out_full_weight_sm;
    Float_t out_Q2_sm;
    Float_t out_W_sm;
    Float_t out_nu_sm;
    Float_t out_xB_sm;
    Float_t out_z_sm;
    Float_t out_theta_e_sm;
    Float_t out_hsdelta_sm;
    Float_t out_hsyptar_sm;
    Float_t out_hsxptar_sm;
    Float_t out_hsytar_sm;
    Float_t out_phi_azimuth_sm;
    Float_t out_hreactz_sm;
    Float_t out_theta_c_sm;
    Float_t out_vtx_z_sm;
    
    // Note: For simulation:
    // - theta_c = atan2(px_e, pz_e) is the electron scattering angle in xz plane
    // - phi_azimuth = atan2(py_e, px_e) is the azimuthal angle
    // - hreactz = (ytar + y_mispoint - x_beam*(cos(theta_c) - yptar*sin(theta_c)))/(sin(theta_c) - yptar*cos(theta_c))
    
    // Create branches in output tree
    outtree->Branch("nclust", &out_nclust, "nclust/I");
    outtree->Branch("clust_E", out_clust_E, "clust_E[2]/F");
    outtree->Branch("clust_X", out_clust_X, "clust_X[2]/F");
    outtree->Branch("clust_Y", out_clust_Y, "clust_Y[2]/F");
    outtree->Branch("mpi0", &out_mpi0, "mpi0/F");
    outtree->Branch("mmiss", &out_mmiss, "mmiss/F");
    outtree->Branch("full_weight", &out_full_weight, "full_weight/F");
    outtree->Branch("Q2", &out_Q2, "Q2/F");
    outtree->Branch("W", &out_W, "W/F");
    outtree->Branch("nu", &out_nu, "nu/F");
    outtree->Branch("xB", &out_xB, "xB/F");
    outtree->Branch("z", &out_z, "z/F");
    outtree->Branch("theta_e", &out_theta_e, "theta_e/F");
    
    outtree->Branch("hsdelta", &out_hsdelta, "hsdelta/F");
    outtree->Branch("hsyptar", &out_hsyptar, "hsyptar/F");
    outtree->Branch("hsxptar", &out_hsxptar, "hsxptar/F");
    outtree->Branch("hsytar", &out_hsytar, "hsytar/F");
    outtree->Branch("phi_azimuth", &out_phi_azimuth, "phi_azimuth/F");
    outtree->Branch("hreactz", &out_hreactz, "hreactz/F");
    outtree->Branch("theta_c", &out_theta_c, "theta_c/F");
    outtree->Branch("vtx_z", &out_vtx_z, "vtx_z/F");
    
    // Create branches for smeared tree
    if (use_smearing) {
        outtree_smeared->Branch("nclust", &out_nclust_sm, "nclust/I");
        outtree_smeared->Branch("clust_E", out_clust_E_sm, "clust_E[2]/F");
        outtree_smeared->Branch("clust_X", out_clust_X_sm, "clust_X[2]/F");
        outtree_smeared->Branch("clust_Y", out_clust_Y_sm, "clust_Y[2]/F");
        outtree_smeared->Branch("mpi0", &out_mpi0_sm, "mpi0/F");
        outtree_smeared->Branch("mmiss", &out_mmiss_sm, "mmiss/F");
        outtree_smeared->Branch("full_weight", &out_full_weight_sm, "full_weight/F");
        outtree_smeared->Branch("Q2", &out_Q2_sm, "Q2/F");
        outtree_smeared->Branch("W", &out_W_sm, "W/F");
        outtree_smeared->Branch("nu", &out_nu_sm, "nu/F");
        outtree_smeared->Branch("xB", &out_xB_sm, "xB/F");
        outtree_smeared->Branch("z", &out_z_sm, "z/F");
        outtree_smeared->Branch("theta_e", &out_theta_e_sm, "theta_e/F");
        outtree_smeared->Branch("hsdelta", &out_hsdelta_sm, "hsdelta/F");
        outtree_smeared->Branch("hsyptar", &out_hsyptar_sm, "hsyptar/F");
        outtree_smeared->Branch("hsxptar", &out_hsxptar_sm, "hsxptar/F");
        outtree_smeared->Branch("hsytar", &out_hsytar_sm, "hsytar/F");
        outtree_smeared->Branch("phi_azimuth", &out_phi_azimuth_sm, "phi_azimuth/F");
        outtree_smeared->Branch("hreactz", &out_hreactz_sm, "hreactz/F");
        outtree_smeared->Branch("theta_c", &out_theta_c_sm, "theta_c/F");
        outtree_smeared->Branch("vtx_z", &out_vtx_z_sm, "vtx_z/F");
    }
    
    // ========================================================================
    // Event Processing Loop
    // ========================================================================
    
    Long64_t nentries = tree->GetEntries();
    Double_t weight_factor = NORMFAC / NEVENTS;
    
    cout << "Processing " << nentries << " events..." << endl;
    cout << "Weight factor: " << weight_factor << endl;
    
    Int_t processed = 0;
    Int_t with_2clusters = 0;
    Int_t filtered_by_hit = 0;
    Int_t filtered_by_energy = 0;
    
    if (USE_INDIVIDUAL_PHOTON_BRANCHES) {
        // ====================================================================
        // Process with individual photon branches
        // ====================================================================
        
        for (Long64_t i = 0; i < nentries; i++) {
            if (i % 50000 == 0) {
                cout << "  Processed " << i << " / " << nentries << " events" << endl;
            }
            
            tree->GetEntry(i);
            
            // Calculate electron scattering angle in xz plane
            // Use transformed coordinates: px_e = sc_e_Py
            const double theta_c = atan2(sc_e_Py, sc_e_Pz);
            
            // Calculate hreactz using the formula
            // hreactz = (ytar + y_mispoint - x_beam*(cos(theta_c) - yptar*sin(theta_c)))/(sin(theta_c) - yptar*cos(theta_c))
            const double ytar = hsytar;
            const double yptar = hsyptar;
            hreactz = (ytar + Y_MISPOINT - x_beam * (cos(theta_c) - yptar * std::abs(sin(theta_c)))) / 
                      (std::abs(sin(theta_c)) +  yptar * cos(theta_c));
            
            // Transform electron kinematics from SIMC lab frame to Hall C replay coordinates
            // Convert from MeV to GeV
            const double Ee = sc_e_E / 1000.0;
            const double px_e = sc_e_Py / 1000.0;
            const double py_e = -sc_e_Px / 1000.0;
            const double pz_e = sc_e_Pz / 1000.0;
            const double phi = atan2(py_e, px_e);
            
            // Fill electron-side variables (saved for ALL events)
            out_hsdelta = hsdelta;
            out_hsyptar = hsyptar;
            out_hsxptar = hsxptar;
            out_hsytar = hsytar;
            out_phi_azimuth = phi;
            out_hreactz = hreactz;
            out_theta_c = theta_c;
            out_vtx_z = vtx_z;
            
            // Initialize NPS/physics variables to sentinel values
            out_nclust = 0;
            out_clust_E[0] = -999;
            out_clust_E[1] = -999;
            out_clust_X[0] = -999;
            out_clust_X[1] = -999;
            out_clust_Y[0] = -999;
            out_clust_Y[1] = -999;
            out_mpi0 = -999;
            out_mmiss = -999;
            out_full_weight = Weight * weight_factor;
            out_Q2 = -999;
            out_W = -999;
            out_nu = -999;
            out_xB = -999;
            out_z = -999;
            out_theta_e = -999;
            
            // Debug: print first few events with more detail
            if (i < 10) {
                cout << "Event " << i << ": phot1_hit=" << phot1_hit << " phot2_hit=" << phot2_hit 
                     << " E1=" << phot1_Ecal << " E2=" << phot2_Ecal 
                     << " x1=" << phot1_hit_x << " y1=" << phot1_hit_y << endl;
            }
            
            // Apply HMS electron cuts (simulation version - no npesum/etotnorm)
            if (!hms_electron_cuts_simulation(hsdelta, hsxptar, hsyptar, hreactz)) {
                outtree->Fill();
                continue;
            }
            
            // Check that both photons have good hits (phot_hit == true)
            if (!phot1_hit || !phot2_hit) {
                filtered_by_hit++;
                outtree->Fill();
                continue;
            }
            with_2clusters++;
            
            // Apply NPS spatial/energy cuts using nps_helper functions
            if (!nps::nps_spatial_energy_cuts(phot1_Ecal, phot1_hit_x, phot1_hit_y, 150.0, DEFAULT_TIME_WINDOW_WRT_150)) {
                filtered_by_energy++;
                outtree->Fill();
                continue;
            }
            if (!nps::nps_spatial_energy_cuts(phot2_Ecal, phot2_hit_x, phot2_hit_y, 150.0, DEFAULT_TIME_WINDOW_WRT_150)) {
                filtered_by_energy++;
                outtree->Fill();
                continue;
            }
            
            // Calculate pion mass using nps helper function
            double mpi0 = nps::invariant_mass_pi0(phot1_Ecal, phot2_Ecal, 
                                                   phot1_hit_x, phot2_hit_x,
                                                   phot1_hit_y, phot2_hit_y, 
                                                   nps::kDefaultZ_NPS_cm);
            
            // Calculate missing mass using nps helper function
            double mmiss = nps::missing_mass_proton_pi0(BEAM_ENERGY, Ee, px_e, py_e, pz_e,
                                                         phot1_Ecal, phot2_Ecal,
                                                         phot1_hit_x, phot1_hit_y,
                                                         phot2_hit_x, phot2_hit_y,
                                                         nps::kDefaultZ_NPS_cm, -17.51);
            
            // Debug: print detailed kinematics for first few events that pass all cuts
            if (processed < 5) {
                const double pbeam = std::sqrt(std::max(0.0, BEAM_ENERGY*BEAM_ENERGY - nps::kElectronMass_GeV*nps::kElectronMass_GeV));
                const double E_in = BEAM_ENERGY + nps::kProtonMass_GeV;
                const double E_out = Ee + phot1_Ecal + phot2_Ecal;
                const double pe_mag = std::sqrt(px_e*px_e + py_e*py_e + pz_e*pz_e);
                cout << "\n=== Event " << i << " (processed #" << processed << ") ===" << endl;
                cout << "Beam: E=" << BEAM_ENERGY << " pz=" << pbeam << endl;
                cout << "Electron: E=" << Ee << " px=" << px_e << " py=" << py_e << " pz=" << pz_e << " |p|=" << pe_mag << endl;
                cout << "Photon1: E=" << phot1_Ecal << " x=" << phot1_hit_x << " y=" << phot1_hit_y << endl;
                cout << "Photon2: E=" << phot2_Ecal << " x=" << phot2_hit_x << " y=" << phot2_hit_y << endl;
                cout << "E_in=" << E_in << " E_out=" << E_out << " E_in-E_out=" << (E_in-E_out) << endl;
                cout << "mpi0=" << mpi0 << " mmiss=" << mmiss << endl;
            }
            
            // Calculate physics variables using nps helper function
            nps::PhysicsVars phys = nps::compute_physics_vars_from_detector(
                                                          BEAM_ENERGY, Ee, px_e, py_e, pz_e,
                                                          phot1_Ecal, phot1_hit_x, phot1_hit_y,
                                                          phot2_Ecal, phot2_hit_x, phot2_hit_y,
                                                          nps::kDefaultZ_NPS_cm, -17.51);
            
            // Fill output variables
            out_nclust = 2;
            out_clust_E[0] = phot1_Ecal;
            out_clust_E[1] = phot2_Ecal;
            out_clust_X[0] = phot1_hit_x;
            out_clust_X[1] = phot2_hit_x;
            out_clust_Y[0] = phot1_hit_y;
            out_clust_Y[1] = phot2_hit_y;
            
            out_mpi0 = mpi0;
            out_mmiss = mmiss;
            out_full_weight = Weight * weight_factor;
            out_Q2 = phys.Q2;
            out_W = phys.W;
            out_nu = phys.nu;
            out_xB = phys.xB;
            out_z = phys.z;
            out_theta_e = phys.theta;
            
            outtree->Fill();
            processed++;
            
            // Process smeared output if enabled
            if (use_smearing) {
                // Get smearing coefficients for this event
                int section1 = get_section(phot1_hit_x, phot1_hit_y);
                int section2 = get_section(phot2_hit_x, phot2_hit_y);
                
                // Use section 0 as default if not in map
                SmearingCoeffs coeff1 = smearing_map.count(section1) ? smearing_map[section1] : smearing_map[0];
                SmearingCoeffs coeff2 = smearing_map.count(section2) ? smearing_map[section2] : smearing_map[0];
                
                // HMS variables remain unsmeared
                Float_t hsdelta_sm = hsdelta;
                Float_t hsyptar_sm = hsyptar;
                Float_t hsxptar_sm = hsxptar;
                Float_t hsytar_sm = hsytar;
                
                // Apply smearing to photon clusters
                // Energy: energy-dependent resolution model
                // Position: additive smearing X/Y + Gaus(0, sigma_pos)
                Float_t phot1_E_sm = apply_energy_smearing(phot1_Ecal, coeff1.mu, coeff1.sigma_E, coeff1.res_A, coeff1.res_B, coeff1.res_C);
                Float_t phot1_X_sm = apply_position_smearing(phot1_hit_x, coeff1.sigma_pos);
                Float_t phot1_Y_sm = apply_position_smearing(phot1_hit_y, coeff1.sigma_pos);
                Float_t phot2_E_sm = apply_energy_smearing(phot2_Ecal, coeff2.mu, coeff2.sigma_E, coeff2.res_A, coeff2.res_B, coeff2.res_C);
                Float_t phot2_X_sm = apply_position_smearing(phot2_hit_x, coeff2.sigma_pos);
                Float_t phot2_Y_sm = apply_position_smearing(phot2_hit_y, coeff2.sigma_pos);
                
                // Recalculate electron kinematics (HMS variables unsmeared)
                const double theta_c_sm = atan2(sc_e_Py, sc_e_Pz);
                const double hreactz_sm = (hsytar + Y_MISPOINT - x_beam * (cos(theta_c_sm) - hsyptar * std::abs(sin(theta_c_sm)))) / 
                                          (std::abs(sin(theta_c_sm)) + hsyptar * cos(theta_c_sm));
                
                const double Ee_sm = sc_e_E / 1000.0;
                const double px_e_sm = sc_e_Py / 1000.0;
                const double py_e_sm = -sc_e_Px / 1000.0;
                const double pz_e_sm = sc_e_Pz / 1000.0;
                const double phi_sm = atan2(py_e_sm, px_e_sm);
                
                // Recalculate physics variables with smeared values
                double mpi0_sm = nps::invariant_mass_pi0(phot1_E_sm, phot2_E_sm, 
                                                         phot1_X_sm, phot2_X_sm,
                                                         phot1_Y_sm, phot2_Y_sm, 
                                                         nps::kDefaultZ_NPS_cm);
                
                double mmiss_sm = nps::missing_mass_proton_pi0(BEAM_ENERGY, Ee_sm, px_e_sm, py_e_sm, pz_e_sm,
                                                               phot1_E_sm, phot2_E_sm,
                                                               phot1_X_sm, phot1_Y_sm,
                                                               phot2_X_sm, phot2_Y_sm,
                                                               nps::kDefaultZ_NPS_cm, -17.51);
                
                nps::PhysicsVars phys_sm = nps::compute_physics_vars_from_detector(
                                                          BEAM_ENERGY, Ee_sm, px_e_sm, py_e_sm, pz_e_sm,
                                                          phot1_E_sm, phot1_X_sm, phot1_Y_sm,
                                                          phot2_E_sm, phot2_X_sm, phot2_Y_sm,
                                                          nps::kDefaultZ_NPS_cm, -17.51);
                
                // Fill smeared output
                out_nclust_sm = 2;
                out_clust_E_sm[0] = phot1_E_sm;
                out_clust_E_sm[1] = phot2_E_sm;
                out_clust_X_sm[0] = phot1_X_sm;
                out_clust_X_sm[1] = phot2_X_sm;
                out_clust_Y_sm[0] = phot1_Y_sm;
                out_clust_Y_sm[1] = phot2_Y_sm;
                out_mpi0_sm = mpi0_sm;
                out_mmiss_sm = mmiss_sm;
                out_full_weight_sm = Weight * weight_factor;
                out_Q2_sm = phys_sm.Q2;
                out_W_sm = phys_sm.W;
                out_nu_sm = phys_sm.nu;
                out_xB_sm = phys_sm.xB;
                out_z_sm = phys_sm.z;
                out_theta_e_sm = phys_sm.theta;
                out_hsdelta_sm = hsdelta_sm;
                out_hsyptar_sm = hsyptar_sm;
                out_hsxptar_sm = hsxptar_sm;
                out_hsytar_sm = hsytar_sm;
                out_phi_azimuth_sm = phi_sm;
                out_hreactz_sm = hreactz_sm;
                out_theta_c_sm = theta_c_sm;
                out_vtx_z_sm = vtx_z;
                
                outtree_smeared->Fill();
            }
        }
        
    } else {
        // ====================================================================
        // Process with cluster vectors (default)
        // ====================================================================
        
        for (Long64_t i = 0; i < nentries; i++) {
            if (i % 50000 == 0) {
                cout << "  Processed " << i << " / " << nentries << " events" << endl;
            }
            
            tree->GetEntry(i);
            
            // Calculate electron scattering angle in xz plane
            // Use transformed coordinates: px_e = sc_e_Py
            const double theta_c = atan2(sc_e_Py, sc_e_Pz);
            
            // Calculate hreactz using the formula
            // hreactz = (ytar + y_mispoint - x_beam*(cos(theta_c) - yptar*sin(theta_c)))/(sin(theta_c) + yptar*cos(theta_c))
            const double ytar = hsytar;
            const double yptar = hsyptar;
            hreactz = (ytar + Y_MISPOINT - x_beam * (cos(theta_c) - yptar * sin(theta_c))) / 
                      (sin(theta_c) + yptar * cos(theta_c));
            
            // Transform electron kinematics from SIMC lab frame to Hall C replay coordinates
            // Convert from MeV to GeV
            const double Ee = sc_e_E / 1000.0;
            const double px_e = sc_e_Py / 1000.0;
            const double py_e = -sc_e_Px / 1000.0;
            const double pz_e = sc_e_Pz / 1000.0;
            const double phi = atan2(py_e, px_e);
            
            // Fill electron-side variables (saved for ALL events)
            out_hsdelta = hsdelta;
            out_hsyptar = hsyptar;
            out_hsxptar = hsxptar;
            out_hsytar = hsytar;
            out_phi_azimuth = phi;
            out_hreactz = hreactz;
            out_theta_c = theta_c;
            out_vtx_z = vtx_z;
            
            // Initialize NPS/physics variables to sentinel values
            out_nclust = 0;
            out_clust_E[0] = -999;
            out_clust_E[1] = -999;
            out_clust_X[0] = -999;
            out_clust_X[1] = -999;
            out_clust_Y[0] = -999;
            out_clust_Y[1] = -999;
            out_mpi0 = -999;
            out_mmiss = -999;
            out_full_weight = Weight * weight_factor;
            out_Q2 = -999;
            out_W = -999;
            out_nu = -999;
            out_xB = -999;
            out_z = -999;
            out_theta_e = -999;
            
            // Debug: print first few events
            if (i < 5) {
                cout << "Event " << i << ": nclust=" << (clust_E ? clust_E->size() : 0) 
                     << " E1=" << (clust_E && clust_E->size() > 0 ? clust_E->at(0) : 0)
                     << " E2=" << (clust_E && clust_E->size() > 1 ? clust_E->at(1) : 0) << endl;
            }
            
            // Apply HMS electron cuts (simulation version - no npesum/etotnorm)
            if (!hms_electron_cuts_simulation(hsdelta, hsxptar, hsyptar, hreactz)) {
                outtree->Fill();
                continue;
            }
            
            // Copy clusters to arrays for processing
            double clusE[MAX_CLUS], clusX[MAX_CLUS], clusY[MAX_CLUS], clusT[MAX_CLUS];
            int nclust = 0;
            if (clust_E && clust_X && clust_Y) {
                nclust = (int) std::min<size_t>(clust_E->size(), MAX_CLUS);
                for (int j=0; j<nclust; ++j) {
                    clusE[j] = (*clust_E)[j];
                    clusX[j] = (*clust_X)[j];
                    clusY[j] = (*clust_Y)[j];
                    clusT[j] = 150.0;  // Simulation doesn't have timing, use default
                }
            }
            
            if (nclust < 2) {
                filtered_by_hit++;
                outtree->Fill();
                continue;
            }
            
            // Merge clusters using nps helper
            nps::mergeClusters(clusE, clusX, clusY, clusT, nclust, 50.0, 2.0);
            const int n_after = nps::packClusters(clusE, clusX, clusY, clusT, nclust);
            
            // Select good clusters by spatial & energy cuts
            vector<int> good_idx;
            good_idx.reserve(8);
            for (int j=0; j<n_after; ++j) {
                if (nps::nps_spatial_energy_cuts(clusE[j], clusX[j], clusY[j], clusT[j], DEFAULT_TIME_WINDOW_WRT_150)) {
                    good_idx.push_back(j);
                }
            }
            
            if (good_idx.size() < 2) {
                filtered_by_hit++;
                outtree->Fill();
                continue;
            }
            
            // Limit to top 4 clusters by energy if more than 4
            if (good_idx.size() > 4) {
                sort(good_idx.begin(), good_idx.end(), [&](int a, int b) { return clusE[a] > clusE[b]; });
                good_idx.resize(4);
            }
            
            with_2clusters++;
            
            // Select pair for pi0
            int sel_i = -1, sel_j = -1;
            if (good_idx.size() == 2) {
                sel_i = good_idx[0];
                sel_j = good_idx[1];
            } else {
                auto pr = nps::choose_best_pair_closest_pi0(good_idx, clusE, clusX, clusY, clusT, 
                                                             nps::kDefaultZ_NPS_cm, nps::kPi0Mass_GeV, 2.0);
                sel_i = pr.first;
                sel_j = pr.second;
                if (sel_i < 0 || sel_j < 0) {
                    filtered_by_energy++;
                    outtree->Fill();
                    continue;
                }
            }
            
            // Calculate pion mass using nps helper function
            double mpi0 = nps::invariant_mass_pi0(clusE[sel_i], clusE[sel_j],
                                                   clusX[sel_i], clusX[sel_j],
                                                   clusY[sel_i], clusY[sel_j],
                                                   nps::kDefaultZ_NPS_cm);
            
            // Calculate missing mass using nps helper function
            double mmiss = nps::missing_mass_proton_pi0(BEAM_ENERGY, Ee, px_e, py_e, pz_e,
                                                         clusE[sel_i], clusE[sel_j],
                                                         clusX[sel_i], clusY[sel_i],
                                                         clusX[sel_j], clusY[sel_j],
                                                         nps::kDefaultZ_NPS_cm, -17.51);
            
            // Debug: print detailed kinematics for first few events that pass all cuts
            if (processed < 50) {
                const double pbeam = std::sqrt(std::max(0.0, BEAM_ENERGY*BEAM_ENERGY - nps::kElectronMass_GeV*nps::kElectronMass_GeV));
                const double E_in = BEAM_ENERGY + nps::kProtonMass_GeV;
                const double E_out = Ee + clusE[sel_i] + clusE[sel_j];
                const double pe_mag = std::sqrt(px_e*px_e + py_e*py_e + pz_e*pz_e);
                cout << "\n=== Event " << i << " (processed #" << processed << ") ===" << endl;
                cout << "Beam: E=" << BEAM_ENERGY << " pz=" << pbeam << endl;
                cout << "Electron: E=" << Ee << " px=" << px_e << " py=" << py_e << " pz=" << pz_e << " |p|=" << pe_mag << endl;
                cout << "Photon1: E=" << clusE[sel_i] << " x=" << clusX[sel_i] << " y=" << clusY[sel_i] << endl;
                cout << "Photon2: E=" << clusE[sel_j] << " x=" << clusX[sel_j] << " y=" << clusY[sel_j] << endl;
                cout << "E_in=" << E_in << " E_out=" << E_out << " E_in-E_out=" << (E_in-E_out) << endl;
                cout << "mpi0=" << mpi0 << " mmiss=" << mmiss << endl;
            }
            
            // Calculate physics variables using nps helper function
            nps::PhysicsVars phys = nps::compute_physics_vars_from_detector(
                                                          BEAM_ENERGY, Ee, px_e, py_e, pz_e,
                                                          clusE[sel_i], clusX[sel_i], clusY[sel_i],
                                                          clusE[sel_j], clusX[sel_j], clusY[sel_j],
                                                          nps::kDefaultZ_NPS_cm, -17.51);
            
            // Fill output variables
            out_nclust = 2;
            out_clust_E[0] = clusE[sel_i];
            out_clust_E[1] = clusE[sel_j];
            out_clust_X[0] = clusX[sel_i];
            out_clust_X[1] = clusX[sel_j];
            out_clust_Y[0] = clusY[sel_i];
            out_clust_Y[1] = clusY[sel_j];
            
            out_mpi0 = mpi0;
            out_mmiss = mmiss;
            out_full_weight = Weight * weight_factor;
            out_Q2 = phys.Q2;
            out_W = phys.W;
            out_nu = phys.nu;
            out_xB = phys.xB;
            out_z = phys.z;
            out_theta_e = phys.theta;
            
            outtree->Fill();
            processed++;
            
            // Process smeared output if enabled
            if (use_smearing) {
                // Get smearing coefficients for this event
                int section1 = get_section(clusX[sel_i], clusY[sel_i]);
                int section2 = get_section(clusX[sel_j], clusY[sel_j]);
                
                // Use section 0 as default if not in map
                SmearingCoeffs coeff1 = smearing_map.count(section1) ? smearing_map[section1] : smearing_map[0];
                SmearingCoeffs coeff2 = smearing_map.count(section2) ? smearing_map[section2] : smearing_map[0];
                
                // HMS variables remain unsmeared
                Float_t hsdelta_sm = hsdelta;
                Float_t hsyptar_sm = hsyptar;
                Float_t hsxptar_sm = hsxptar;
                Float_t hsytar_sm = hsytar;
                
                // Apply smearing to photon clusters
                // Energy: energy-dependent resolution model
                // Position: additive smearing X/Y + Gaus(0, sigma_pos)
                Float_t clus1_E_sm = apply_energy_smearing(clusE[sel_i], coeff1.mu, coeff1.sigma_E, coeff1.res_A, coeff1.res_B, coeff1.res_C);
                Float_t clus1_X_sm = apply_position_smearing(clusX[sel_i], coeff1.sigma_pos);
                Float_t clus1_Y_sm = apply_position_smearing(clusY[sel_i], coeff1.sigma_pos);
                Float_t clus2_E_sm = apply_energy_smearing(clusE[sel_j], coeff2.mu, coeff2.sigma_E, coeff2.res_A, coeff2.res_B, coeff2.res_C);
                Float_t clus2_X_sm = apply_position_smearing(clusX[sel_j], coeff2.sigma_pos);
                Float_t clus2_Y_sm = apply_position_smearing(clusY[sel_j], coeff2.sigma_pos);
                
                // Recalculate electron kinematics (HMS variables unsmeared)
                const double theta_c_sm = atan2(sc_e_Py, sc_e_Pz);
                const double hreactz_sm = (hsytar + Y_MISPOINT - x_beam * (cos(theta_c_sm) - hsyptar * sin(theta_c_sm))) / 
                                          (sin(theta_c_sm) + hsyptar * cos(theta_c_sm));
                
                const double Ee_sm = sc_e_E / 1000.0;
                const double px_e_sm = sc_e_Py / 1000.0;
                const double py_e_sm = -sc_e_Px / 1000.0;
                const double pz_e_sm = sc_e_Pz / 1000.0;
                const double phi_sm = atan2(py_e_sm, px_e_sm);
                
                // Recalculate physics variables with smeared values
                double mpi0_sm = nps::invariant_mass_pi0(clus1_E_sm, clus2_E_sm,
                                                         clus1_X_sm, clus2_X_sm,
                                                         clus1_Y_sm, clus2_Y_sm,
                                                         nps::kDefaultZ_NPS_cm);
                
                double mmiss_sm = nps::missing_mass_proton_pi0(BEAM_ENERGY, Ee_sm, px_e_sm, py_e_sm, pz_e_sm,
                                                               clus1_E_sm, clus2_E_sm,
                                                               clus1_X_sm, clus1_Y_sm,
                                                               clus2_X_sm, clus2_Y_sm,
                                                               nps::kDefaultZ_NPS_cm, -17.51);
                
                nps::PhysicsVars phys_sm = nps::compute_physics_vars_from_detector(
                                                          BEAM_ENERGY, Ee_sm, px_e_sm, py_e_sm, pz_e_sm,
                                                          clus1_E_sm, clus1_X_sm, clus1_Y_sm,
                                                          clus2_E_sm, clus2_X_sm, clus2_Y_sm,
                                                          nps::kDefaultZ_NPS_cm, -17.51);
                
                // Fill smeared output
                out_nclust_sm = 2;
                out_clust_E_sm[0] = clus1_E_sm;
                out_clust_E_sm[1] = clus2_E_sm;
                out_clust_X_sm[0] = clus1_X_sm;
                out_clust_X_sm[1] = clus2_X_sm;
                out_clust_Y_sm[0] = clus1_Y_sm;
                out_clust_Y_sm[1] = clus2_Y_sm;
                out_mpi0_sm = mpi0_sm;
                out_mmiss_sm = mmiss_sm;
                out_full_weight_sm = Weight * weight_factor;
                out_Q2_sm = phys_sm.Q2;
                out_W_sm = phys_sm.W;
                out_nu_sm = phys_sm.nu;
                out_xB_sm = phys_sm.xB;
                out_z_sm = phys_sm.z;
                out_theta_e_sm = phys_sm.theta;
                out_hsdelta_sm = hsdelta_sm;
                out_hsyptar_sm = hsyptar_sm;
                out_hsxptar_sm = hsxptar_sm;
                out_hsytar_sm = hsytar_sm;
                out_phi_azimuth_sm = phi_sm;
                out_hreactz_sm = hreactz_sm;
                out_theta_c_sm = theta_c_sm;
                out_vtx_z_sm = vtx_z;
                
                outtree_smeared->Fill();
            }
        }
    }
    
    cout << "\n=== Summary ===" << endl;
    cout << "Total entries processed: " << nentries << endl;
    if (USE_INDIVIDUAL_PHOTON_BRANCHES) {
        cout << "Filtered by photon hit requirement: " << filtered_by_hit << endl;
        cout << "Passed photon hit, filtered by energy: " << filtered_by_energy << endl;
    }
    cout << "Events with 2 clusters: " << with_2clusters << endl;
    cout << "Events written to output: " << processed << endl;
    
    // Write and close output files
    outfile->Write();
    cout << "\nOutput file saved: " << output_file << endl;
    cout << "Output tree: " << outtree->GetEntries() << " entries" << endl;
    
    if (use_smearing && outfile_smeared) {
        outfile_smeared->Write();
        cout << "\nSmeared output file saved: " << output_file_smeared << endl;
        cout << "Smeared output tree: " << outtree_smeared->GetEntries() << " entries" << endl;
        outfile_smeared->Close();
        delete outfile_smeared;
    }
    
    outfile->Close();
    infile->Close();
    
    delete outfile;
    delete infile;
    
    cout << "Analysis complete!" << endl;
}

// ============================================================================
// Execution
// ============================================================================

int main()
{
    simc_pi0_analysis();
    return 0;
}
